<?php

$map  -> option  ( 'titlebar_default' );

$map  -> option  ( 'titlebar_styles' )
      -> sub     ( 'indicator', array() )
      -> sub     ( 'name', array() )
      -> sub     ( 'background_style', array() )
      -> sub     ( 'background_image', array() )
      -> sub     ( 'background_position', array() )
      -> sub     ( 'background_color', array() )
      -> sub     ( 'color', array() )
      -> sub     ( 'title_color', array() )
      -> sub     ( 'border_bottom', array() )
      -> sub     ( 'link_color', array() )
      -> sub     ( 'link_decoration', array() )
      -> sub     ( 'link_hover_color', array() )
      -> sub     ( 'link_hover_decoration', array() )
      -> sub     ( 'bc_background_color', array() )
      -> sub     ( 'bc_border_color', array() )
      -> sub     ( 'bc_link_color', array() )
      -> sub     ( 'bc_link_hover_color', array() )
      -> sub     ( 'padding_top', array() )
      -> sub     ( 'padding_bottom', array() )
      -> sub     ( 'parallax', array() )
;

$map  -> option  ( 'button_colors' )
      -> sub     ( 'indicator', array() )
      -> sub     ( 'name', array() )
      -> sub     ( 'gradient_0', array() )
      -> sub     ( 'gradient_1', array() )
      -> sub     ( 'gradient_hover_0', array() )
      -> sub     ( 'gradient_hover_1', array() )
      -> sub     ( 'color', array() )
      -> sub     ( 'color_hover', array() )
      -> sub     ( 'border_color', array() )
      -> sub     ( 'border_color_hover', array() )
      -> sub     ( 'shadow_color', array() )
      -> sub     ( 'shadow_color_hover', array() )
      -> sub     ( 'shadow_direction', array() )
      -> sub     ( 'shadow_direction_hover', array() )
;

$map  -> option  ( 'section_styles' )
      -> sub     ( 'indicator', array() )
      -> sub     ( 'name', array() )
      -> sub     ( 'gradient_0', array() )
      -> sub     ( 'gradient_1', array() )
      -> sub     ( 'background_image', array() )
      -> sub     ( 'background_position', array() )
      -> sub     ( 'background_style', array() )
      -> sub     ( 'border_top', array() )
      -> sub     ( 'border_bottom', array() )
      -> sub     ( 'color', array() )
      -> sub     ( 'heading_color', array() )
      -> sub     ( 'link_color', array() )
      -> sub     ( 'link_decoration', array() )
      -> sub     ( 'link_hover_color', array() )
      -> sub     ( 'link_hover_decoration', array() )
      -> sub     ( 'shadow_style', array() )
      -> sub     ( 'overflow', array() )
      -> sub     ( 'parallax', array() )
;